//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krappsena
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int idArea { get; set; }
        public string descArea { get; set; }
        public string estaArea { get; set; }
    }
}
