//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krappsena
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detallederegistrodenovedad
    {
        public int idDeno { get; set; }
        public Nullable<int> idReno { get; set; }
        public Nullable<int> idNove { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> estaDeno { get; set; }
    }
}
