//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krappsena
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int idEmpl { get; set; }
        public string docuEmpl { get; set; }
        public string nombUsua { get; set; }
        public string apelEmpl { get; set; }
        public string teleUsua { get; set; }
        public string direUsua { get; set; }
        public string emaiUsua { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> idCarg { get; set; }
        public Nullable<int> idSede { get; set; }
        public Nullable<int> idTiem { get; set; }
        public Nullable<int> estaEmp { get; set; }
    }
}
