//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krappsena
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krappsenaEntities : DbContext
    {
        public krappsenaEntities()
            : base("name=krappsenaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Detallederegistrodenovedad> Detallederegistrodenovedad { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<Registrodenovedad> Registrodenovedad { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Tipodeempleados> Tipodeempleados { get; set; }
        public virtual DbSet<Tipodenovedad> Tipodenovedad { get; set; }
    }
}
