//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krappsena
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrodenovedad
    {
        public int idReno { get; set; }
        public Nullable<System.DateTime> fechReno { get; set; }
        public Nullable<System.DateTime> horaReno { get; set; }
        public Nullable<int> idEmp { get; set; }
        public Nullable<int> idCate { get; set; }
        public Nullable<int> estaReno { get; set; }
    }
}
